const env = {
  SERVER_PATH: import.meta.env.VITE_SERVER_PATH,
  FIREBASE_APP_ID: import.meta.env.FIREBASE_APP_ID,
  VITE_FIREBASE_KEY: import.meta.env.VITE_FIREBASE_KEY,
  VITE_FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  VITE_FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID,
  VITE_FIREBASE_MEASUREMENT_ID: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
};

export default env;
